### PR TITLE
fix issue 56

### PR DESCRIPTION
**Pull request by sandyharvie**
Fixes https://github.com/odygrd/quill/issues/56.

### CODE REVIEW

**Comment by odygrd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- quill/test/PatternFormatterTest.cpp  6
         

Clones removed
==============
+ quill/include/quill/PatternFormatter.h  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6366702&bid=20661114)

**Comment by odygrd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- quill/test/PatternFormatterTest.cpp  6
         

Clones removed
==============
+ quill/include/quill/PatternFormatter.h  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6366702&bid=20661114)

**Comment by odygrd** [comment]
Thanks a lot for reporting and submitting a fix on this. I made a few minor changes and also fixed windows build. (windows don't support `%s` in `strftime`)

**Comment by odygrd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- quill/test/PatternFormatterTest.cpp  6
         

Clones removed
==============
+ quill/include/quill/PatternFormatter.h  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6366702&bid=20661114)

**Comment by odygrd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- quill/test/PatternFormatterTest.cpp  6
         

Clones removed
==============
+ quill/include/quill/PatternFormatter.h  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6366702&bid=20661114)

**Comment by sandyharvie** [comment]
Any idea when you might put this into a new release?

**Comment by odygrd** [comment]
Planning to do a new release `1.5.0` in the next two weeks or so. The problem with releases is that i also maintain the package manager PRs myself and on every release I have to update them : )
Are you using any package manager that you would like this release to be in as a priority ?

**Comment by sandyharvie** [comment]
Nope––the tarball on the releases page is all I need!

**Comment by odygrd** [comment]
Hello, there is now a 1.5.0 release tarball available. @sandyharvie

**Pull request merged**
