### PR TITLE
simplify example for log level filter

### PR DESCRIPTION
**Pull request by zhangzq**

### CODE REVIEW

**Comment by odygrd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ examples/example_filters.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6374241&bid=20681837)

**Comment by zhangzq** [comment]
> # [Codecov](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=h1) Report
> > Merging [#58](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=desc) into [master](https://codecov.io/gh/odygrd/quill/commit/a420443487c158d589a492d5023e8421121bfe00?el=desc) will **decrease** coverage by `0.04%`.
> > The diff coverage is `n/a`.
> 
> [Impacted file tree graph](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=tree)
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master      #58      +/-   ##
> ==========================================
> - Coverage   88.63%   88.58%   -0.05%     
> ==========================================
>   Files          65       65              
>   Lines        1874     1875       +1     
>   Branches      200      200              
> ==========================================
>   Hits         1661     1661              
> - Misses        213      214       +1     
> ```
> 
> [Impacted Files](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=tree)	Coverage Δ	
> [quill/src/detail/misc/Os.cpp](https://codecov.io/gh/odygrd/quill/pull/58/diff?src=pr&el=tree#diff-cXVpbGwvc3JjL2RldGFpbC9taXNjL09zLmNwcA==)	`58.27% <0.00%> (-0.39%)`	⬇️
> [Continue to review full report at Codecov](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=footer). Last update [a420443...9009de4](https://codecov.io/gh/odygrd/quill/pull/58?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

What this means? I didn't modify the file `quill/src/detail/misc/Os.cpp`.

**Comment by zhangzq** [comment]
> Codacy Here is an overview of what got changed by this pull request:
> 
> ```diff
> Clones removed
> ==============
> + examples/example_filters.cpp  -2
>          
> ```
> 
> See the complete overview on [Codacy](https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6374241&bid=20681837)

Sorry I'm not familiar with this, and I got nothing at https://app.codacy.com/manual/odygrd/quill/pullRequest?prid=6374241&bid=20681837. What can I do for this?

**Comment by odygrd** [comment]
thanks for the PR, I merged this into the other existing PR

**Pull request closed without merging**
